# Generated by Django 4.2.5 on 2023-09-29 23:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_first_name', models.CharField(max_length=100, verbose_name='Имя ветеринара:')),
                ('doc_last_name', models.CharField(max_length=100, verbose_name='Фамилия ветеринара:')),
            ],
        ),
        migrations.CreateModel(
            name='PetIllnessName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('illness_name', models.CharField(max_length=100, verbose_name='Название болезни:')),
            ],
        ),
        migrations.CreateModel(
            name='PetIllnessStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('illness_stage', models.CharField(choices=[('Лёгкая', 'Лёгкая'), ('Средняя', 'Средняя'), ('Тяжёлая', 'Тяжёлая')], max_length=100, verbose_name='Форма болезни:')),
            ],
        ),
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drug_title', models.CharField(max_length=100, verbose_name='Название лекарства:')),
                ('drug_dose', models.CharField(max_length=100, verbose_name='Дозировка:')),
                ('drug_intake', models.IntegerField(verbose_name='Принимать Х раз в день:')),
                ('drug_period', models.IntegerField(verbose_name='Принимать Х дней:')),
            ],
        ),
        migrations.CreateModel(
            name='VetClinic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_name', models.CharField(max_length=100, verbose_name='Кличка:')),
                ('pet_breed', models.CharField(max_length=100, verbose_name='Порода:')),
                ('pet_age', models.IntegerField(verbose_name='Возраст:')),
                ('assigned_doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vetclinic.doctors', verbose_name='Лечащий врач:')),
                ('pet_illness_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vetclinic.petillnessname', verbose_name='Название болезни:')),
                ('pet_illness_stage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vetclinic.petillnessstage', verbose_name='Форма болезни:')),
                ('pet_treatment', models.ManyToManyField(to='vetclinic.treatment', verbose_name='Название лекарства:')),
            ],
        ),
    ]
