# Generated by Django 4.2.5 on 2023-09-25 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PetIllness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('illness_name', models.CharField(max_length=100)),
                ('illness_stage', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drug_title', models.CharField(max_length=100)),
                ('drug_dose', models.CharField(max_length=100)),
                ('drug_intake', models.CharField(max_length=100)),
                ('drug_period', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='VetClinic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_name', models.CharField(max_length=100)),
                ('pet_breed', models.CharField(max_length=100)),
                ('pet_age', models.IntegerField()),
                ('pet_illness', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogue.petillness')),
                ('pet_treatment', models.ManyToManyField(to='catalogue.treatment')),
            ],
        ),
    ]
