# Generated by Django 4.2.5 on 2023-09-29 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='actor_birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date of birth:'),
        ),
        migrations.AlterField(
            model_name='actor',
            name='actor_country',
            field=models.CharField(max_length=100, verbose_name='Born in _ country:'),
        ),
        migrations.AlterField(
            model_name='actor',
            name='actor_first_name',
            field=models.CharField(max_length=100, verbose_name='Actor first name:'),
        ),
        migrations.AlterField(
            model_name='actor',
            name='actor_last_name',
            field=models.CharField(max_length=100, verbose_name='Actor last name:'),
        ),
        migrations.AlterField(
            model_name='agerestriction',
            name='age_restr',
            field=models.CharField(choices=[('G', 'G'), ('PG', 'PG'), ('PG-13', 'PG-13'), ('R', 'R'), ('NC-17', 'NC-17')], max_length=20, verbose_name='Age restriction:'),
        ),
        migrations.AlterField(
            model_name='country',
            name='movie_country',
            field=models.CharField(max_length=100, verbose_name='Production country:'),
        ),
        migrations.AlterField(
            model_name='director',
            name='director_first_name',
            field=models.CharField(max_length=100, verbose_name='Director first name:'),
        ),
        migrations.AlterField(
            model_name='director',
            name='director_last_name',
            field=models.CharField(max_length=100, verbose_name='Director last name:'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='genre_name',
            field=models.CharField(max_length=100, verbose_name='Genre:'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='actors',
            field=models.ManyToManyField(to='catalogue.actor', verbose_name='Actors list:'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='rating',
            field=models.FloatField(verbose_name='Critics score:'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='summary',
            field=models.TextField(max_length=9999, verbose_name='Movie synopsis:'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Movie title:'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='year',
            field=models.IntegerField(verbose_name='Production year(s):'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='subscription_type',
            field=models.CharField(choices=[('bronze', 'BRONZE'), ('silver', 'SILVER'), ('gold', 'GOLD')], max_length=100, verbose_name='Subscription type:'),
        ),
    ]
