# Generated by Django 4.2.5 on 2023-09-26 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_first_name', models.CharField(max_length=100)),
                ('doc_last_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='petillness',
            name='illness_stage',
            field=models.CharField(choices=[('Light', 'Light'), ('Mild', 'Mild'), ('Severe', 'Severe')], max_length=100),
        ),
    ]
