# Generated by Django 4.2.5 on 2023-10-07 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0003_movie_movie_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='actor_country',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Born in:'),
        ),
    ]
