# Generated by Django 4.2.5 on 2023-09-26 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0004_vetclinic_assigned_doctor'),
    ]

    operations = [
        migrations.CreateModel(
            name='PetIllnessName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('illness_name', models.CharField(max_length=100, verbose_name='Название болезни:')),
            ],
        ),
        migrations.RemoveField(
            model_name='petillness',
            name='illness_name',
        ),
        migrations.AlterField(
            model_name='doctors',
            name='doc_first_name',
            field=models.CharField(max_length=100, verbose_name='Имя ветеринара:'),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='doc_last_name',
            field=models.CharField(max_length=100, verbose_name='Фамилия ветеринара:'),
        ),
    ]
