# Generated by Django 4.2.5 on 2023-09-26 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0005_petillnessname_remove_petillness_illness_name_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PetIllness',
            new_name='PetIllnessStage',
        ),
        migrations.RenameField(
            model_name='vetclinic',
            old_name='pet_illness',
            new_name='pet_illness_stage',
        ),
        migrations.AddField(
            model_name='vetclinic',
            name='pet_illness_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogue.petillnessname'),
        ),
    ]
