# Generated by Django 4.2.5 on 2023-09-26 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0006_rename_petillness_petillnessstage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petillnessstage',
            name='illness_stage',
            field=models.CharField(choices=[('Лёгкая', 'Лёгкая'), ('Средняя', 'Средняя'), ('Тяжёлая', 'Тяжёлая')], max_length=100, verbose_name='Форма болезни:'),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='drug_dose',
            field=models.CharField(max_length=100, verbose_name='Дозировка:'),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='drug_intake',
            field=models.IntegerField(verbose_name='Принимать Х раз в день:'),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='drug_period',
            field=models.IntegerField(verbose_name='Принимать Х дней:'),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='drug_title',
            field=models.CharField(max_length=100, verbose_name='Название лекарства:'),
        ),
        migrations.AlterField(
            model_name='vetclinic',
            name='assigned_doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogue.doctors', verbose_name='Лечащий врач:'),
        ),
        migrations.AlterField(
            model_name='vetclinic',
            name='pet_age',
            field=models.IntegerField(verbose_name='Возраст:'),
        ),
        migrations.AlterField(
            model_name='vetclinic',
            name='pet_breed',
            field=models.CharField(max_length=100, verbose_name='Порода:'),
        ),
        migrations.AlterField(
            model_name='vetclinic',
            name='pet_illness_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogue.petillnessname', verbose_name='Название болезни:'),
        ),
        migrations.AlterField(
            model_name='vetclinic',
            name='pet_illness_stage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogue.petillnessstage', verbose_name='Форма болезни:'),
        ),
        migrations.AlterField(
            model_name='vetclinic',
            name='pet_name',
            field=models.CharField(max_length=100, verbose_name='Кличка:'),
        ),
        migrations.AlterField(
            model_name='vetclinic',
            name='pet_treatment',
            field=models.ManyToManyField(to='catalogue.treatment', verbose_name='Название лекарства:'),
        ),
    ]
