# Generated by Django 4.2.5 on 2023-09-30 00:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0007_alter_petillnessstage_illness_stage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_first_name', models.CharField(max_length=100, verbose_name='Actor first name:')),
                ('actor_last_name', models.CharField(max_length=100, verbose_name='Actor last name:')),
                ('actor_birth_date', models.DateField(blank=True, null=True, verbose_name='Date of birth:')),
                ('actor_country', models.CharField(max_length=100, verbose_name='Born in _ country:')),
            ],
        ),
        migrations.CreateModel(
            name='AgeRestriction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_restr', models.CharField(choices=[('G', 'G'), ('PG', 'PG'), ('PG-13', 'PG-13'), ('R', 'R'), ('NC-17', 'NC-17')], max_length=20, verbose_name='Age restriction:')),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_country', models.CharField(max_length=100, verbose_name='Production country:')),
            ],
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('director_first_name', models.CharField(max_length=100, verbose_name='Director first name:')),
                ('director_last_name', models.CharField(max_length=100, verbose_name='Director last name:')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre_name', models.CharField(max_length=100, verbose_name='Genre:')),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Movie title:')),
                ('rating', models.FloatField(verbose_name='Critics score:')),
                ('summary', models.TextField(max_length=9999, verbose_name='Movie synopsis:')),
                ('year', models.IntegerField(verbose_name='Production year(s):')),
                ('actors', models.ManyToManyField(to='catalogue.actor', verbose_name='Actors list:')),
                ('age_rate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogue.agerestriction')),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogue.country')),
                ('director', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogue.director')),
                ('genre', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='catalogue.genre')),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_type', models.CharField(choices=[('bronze', 'BRONZE'), ('silver', 'SILVER'), ('gold', 'GOLD')], max_length=100, verbose_name='Subscription type:')),
            ],
        ),
        migrations.RemoveField(
            model_name='vetclinic',
            name='assigned_doctor',
        ),
        migrations.RemoveField(
            model_name='vetclinic',
            name='pet_illness_name',
        ),
        migrations.RemoveField(
            model_name='vetclinic',
            name='pet_illness_stage',
        ),
        migrations.RemoveField(
            model_name='vetclinic',
            name='pet_treatment',
        ),
        migrations.DeleteModel(
            name='Doctors',
        ),
        migrations.DeleteModel(
            name='PetIllnessName',
        ),
        migrations.DeleteModel(
            name='PetIllnessStage',
        ),
        migrations.DeleteModel(
            name='Treatment',
        ),
        migrations.DeleteModel(
            name='VetClinic',
        ),
        migrations.AddField(
            model_name='movie',
            name='subscription',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogue.subscription'),
        ),
    ]
